# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 11:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20190304_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='location_name',
        ),
        migrations.AddField(
            model_name='images',
            name='location',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='photos.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='category',
            field=models.ForeignKey(default=datetime.datetime(2019, 3, 4, 11, 58, 13, 157396, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='photos.Category'),
            preserve_default=False,
        ),
    ]
