# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-06 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20190304_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='title',
            new_name='name',
        ),
    ]
